apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app.kubernetes.io/name: hello
    app.kubernetes.io/part-of: platform-services
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hello
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
