#!/usr/bin/env bash
# Unit tests for the phase-6 workload1 cluster scaffolding (REQ-WL-01..05).
#
# Three assertion groups:
#   1. The workload1 spoke add-ons are generated by the SHARED base-add-on
#      ApplicationSets (ADR-0010 — the former per-file workload1-* mirror
#      Applications collapsed into them): ingress-nginx / external-dns / hello
#      must fan out to EVERY spoke (their generator selects cluster-role=spoke
#      and must NOT pin short-name), name their generated Applications by the
#      short-name label (so workload1-* names emerge from the workload1
#      Secret), keep the wave ordering (ingress/dns 20 < hello 30), and the
#      external-dns set must select the per-cluster values file by short-name
#      (workload1's disjoint TXT identity lives in workload1-values.yaml).
#   2. The cluster-creation Application (argocd/apps/workload1-cluster.yaml) is
#      MANUAL-SYNC: project=k8-platform, no syncPolicy.automated block, header
#      documents the manual-sync choice, path resolves to clusters/workload1,
#      and the XR + namespace it ships are well-formed.
#   3. The workload1 external-dns scoping is DISJOINT from BOTH the hub
#      (management.<domain> / k8-platform-mgmt) AND the platform spoke
#      (platform.<domain> / k8-platform-platform) — all three share the one
#      account Route53 zone (auto-008 §6 / S3) — and carries the auto-012
#      IRSA/zone pins (SA name, --aws-zone-match-parent) the ADR-0010 review
#      found missing.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/lib/test-helpers.sh"
require_tool yq

ROOT="$HERE/../.."
SPOKE_DIR="$ROOT/argocd/apps/spoke"
FAIL=0

# ───────────────────────────────────────────────────────────────────────────
# 1. The shared base-add-on ApplicationSets fan out to every spoke.
# ───────────────────────────────────────────────────────────────────────────
# The old per-file mirrors must stay gone (their reappearance would mean the
# collapse regressed).
for old in workload1-ingress-nginx.yaml workload1-external-dns.yaml workload1-hello.yaml; do
  [ -e "$SPOKE_DIR/$old" ] && { echo "FAIL: $old reappeared — workload1 add-ons are generated by the shared ApplicationSets (ADR-0010)"; FAIL=1; } \
    || echo "ok: no per-file mirror $old"
done

check_base_addon() {
  local file="$1" want_wave="$2" base
  base="$(basename "$file")"
  [ -f "$file" ] || { echo "FAIL: $file missing"; FAIL=1; return; }

  # Fans out to ALL spokes: selects cluster-role=spoke, does NOT pin short-name.
  local role pin
  role="$(yq -r '.spec.generators[0].clusters.selector.matchLabels."k8-platform.io/cluster-role"' "$file")"
  pin="$(yq -r '.spec.generators[0].clusters.selector.matchLabels."k8-platform.io/short-name"' "$file")"
  [ "$role" = "spoke" ] && echo "ok[$base]: selects cluster-role=spoke" \
    || { echo "FAIL[$base]: generator must select k8-platform.io/cluster-role=spoke (got $role)"; FAIL=1; }
  [ "$pin" = "null" ] && echo "ok[$base]: short-name NOT pinned (fans out to workload spokes)" \
    || { echo "FAIL[$base]: base add-on must not pin short-name=$pin — workload1 would never be generated"; FAIL=1; }

  # Generated names carry the short-name prefix (workload1-* emerges).
  local tname
  tname="$(yq -r '.spec.template.metadata.name' "$file")"
  case "$tname" in
    '{{index .metadata.labels "k8-platform.io/short-name"}}-'*)
      echo "ok[$base]: generated name is short-name-prefixed";;
    *)
      echo "FAIL[$base]: template metadata.name must be short-name-prefixed (got $tname)"; FAIL=1;;
  esac

  # Wave ordering preserved on the generated Applications.
  local wave
  wave="$(yq -r '.spec.template.metadata.annotations."argocd.argoproj.io/sync-wave"' "$file")"
  [ "$wave" = "$want_wave" ] && echo "ok[$base]: template sync-wave=$want_wave" \
    || { echo "FAIL[$base]: template sync-wave=$wave, want $want_wave"; FAIL=1; }
}

check_base_addon "$SPOKE_DIR/ingress-nginx.yaml" "20"
check_base_addon "$SPOKE_DIR/external-dns.yaml" "20"
check_base_addon "$SPOKE_DIR/hello.yaml" "30"

# external-dns: per-cluster values file selected by short-name — workload1's
# disjoint TXT identity (txtOwnerId/txtPrefix/domainFilters) rides its own
# committed file, not the template.
EDNS="$SPOKE_DIR/external-dns.yaml"
if [ -f "$EDNS" ]; then
  if yq -r '.spec.template.spec.sources[]?.helm.valueFiles[]?' "$EDNS" \
      | grep -q '^\$values/platform-services/external-dns/{{index .metadata.labels "k8-platform.io/short-name"}}-values.yaml$'; then
    echo "ok[external-dns]: valueFiles switch on short-name (<short-name>-values.yaml)"
  else
    echo "FAIL[external-dns]: template must select \$values/platform-services/external-dns/<short-name>-values.yaml"; FAIL=1
  fi
fi

# hello: subdomain comes from the per-cluster fact, never hard-coded — that is
# what makes hello.workload1.<domain> vs hello.platform.<domain> disjoint.
HELLO="$SPOKE_DIR/hello.yaml"
if [ -f "$HELLO" ]; then
  hsub="$(yq -r '.spec.template.spec.source.helm.valuesObject.subdomain' "$HELLO")"
  case "$hsub" in
    *'k8-platform.io/subdomain'*) echo "ok[hello]: subdomain templated from the cluster fact";;
    *) echo "FAIL[hello]: subdomain must be templated from the k8-platform.io/subdomain fact (got $hsub)"; FAIL=1;;
  esac
fi

# Both per-cluster values files exist under the short-name convention.
for vf in spoke-values.yaml workload1-values.yaml; do
  [ -f "$ROOT/platform-services/external-dns/$vf" ] && echo "ok: external-dns/$vf present" \
    || { echo "FAIL: platform-services/external-dns/$vf missing (short-name convention)"; FAIL=1; }
done

# ───────────────────────────────────────────────────────────────────────────
# 2. The cluster-creation Application is MANUAL-SYNC.
# ───────────────────────────────────────────────────────────────────────────
CLUSTER_APP="$ROOT/argocd/apps/workload1-cluster.yaml"
[ -f "$CLUSTER_APP" ] || { echo "FAIL: $CLUSTER_APP missing"; FAIL=1; }

if [ -f "$CLUSTER_APP" ]; then
  cproj="$(yq -r '.spec.project' "$CLUSTER_APP")"
  [ "$cproj" = "k8-platform" ] && echo "ok[workload1-cluster]: project=k8-platform" \
    || { echo "FAIL[workload1-cluster]: project=$cproj, want k8-platform"; FAIL=1; }

  # No automated sync block (manual sync only).
  cauto="$(yq -r '.spec.syncPolicy.automated' "$CLUSTER_APP")"
  [ "$cauto" = "null" ] && echo "ok[workload1-cluster]: no syncPolicy.automated (manual sync)" \
    || { echo "FAIL[workload1-cluster]: syncPolicy.automated present — must be manual sync"; FAIL=1; }

  # Header documents the manual-sync choice (the literal test_argocd_app_revision_
  # pinned.sh keys on to accept the absent automated block).
  if grep -q "manual sync only\|without automated sync\|no syncPolicy.automated" "$CLUSTER_APP"; then
    echo "ok[workload1-cluster]: manual-sync choice documented in header"
  else
    echo "FAIL[workload1-cluster]: header must document the manual-sync choice"; FAIL=1
  fi

  # path resolves to clusters/workload1 (a real dir).
  cpath="$(yq -r '.spec.source.path' "$CLUSTER_APP")"
  [ "$cpath" = "clusters/workload1" ] && [ -d "$ROOT/$cpath" ] \
    && echo "ok[workload1-cluster]: source.path=clusters/workload1 (exists)" \
    || { echo "FAIL[workload1-cluster]: source.path=$cpath not clusters/workload1 or missing"; FAIL=1; }

  crev="$(yq -r '.spec.source.targetRevision' "$CLUSTER_APP")"
  case "$crev" in
    ""|null|HEAD) echo "FAIL[workload1-cluster]: targetRevision '$crev' not pinned"; FAIL=1;;
    *) echo "ok[workload1-cluster]: targetRevision pinned ($crev)";;
  esac
fi

# The XR + namespace the cluster app ships are well-formed.
XR="$ROOT/clusters/workload1/workload-cluster.yaml"
NS="$ROOT/clusters/workload1/00-namespace.yaml"
[ -f "$XR" ] || { echo "FAIL: $XR missing"; FAIL=1; }
[ -f "$NS" ] || { echo "FAIL: $NS missing"; FAIL=1; }

if [ -f "$XR" ]; then
  xkind="$(yq -r '.kind' "$XR")"
  [ "$xkind" = "XPlatformCluster" ] && echo "ok[XR]: kind=XPlatformCluster (XRD reuse)" \
    || { echo "FAIL[XR]: kind=$xkind, want XPlatformCluster"; FAIL=1; }
  xns="$(yq -r '.metadata.namespace' "$XR")"
  [ "$xns" = "workload1" ] && echo "ok[XR]: namespace=workload1 (v2 namespaced XR)" \
    || { echo "FAIL[XR]: namespace=$xns, want workload1"; FAIL=1; }
  xname="$(yq -r '.spec.name' "$XR")"
  [ "$xname" = "k8-platform-workload1" ] && echo "ok[XR]: spec.name=k8-platform-workload1" \
    || { echo "FAIL[XR]: spec.name=$xname, want k8-platform-workload1"; FAIL=1; }
  xsub="$(yq -r '.spec.dns.subdomain' "$XR")"
  [ "$xsub" = "workload1" ] && echo "ok[XR]: dns.subdomain=workload1" \
    || { echo "FAIL[XR]: dns.subdomain=$xsub, want workload1"; FAIL=1; }
  xwave="$(yq -r '.metadata.annotations."argocd.argoproj.io/sync-wave"' "$XR")"
  [ "$xwave" = "10" ] && echo "ok[XR]: sync-wave=10 (mirrors platform XR)" \
    || { echo "FAIL[XR]: sync-wave=$xwave, want 10"; FAIL=1; }
fi

if [ -f "$NS" ]; then
  nsname="$(yq -r '.metadata.name' "$NS")"
  nskind="$(yq -r '.kind' "$NS")"
  { [ "$nskind" = "Namespace" ] && [ "$nsname" = "workload1" ]; } \
    && echo "ok[NS]: Namespace workload1" \
    || { echo "FAIL[NS]: kind=$nskind name=$nsname, want Namespace/workload1"; FAIL=1; }
fi

# ───────────────────────────────────────────────────────────────────────────
# 3. workload1 external-dns scoping disjoint from BOTH hub AND platform spoke.
# ───────────────────────────────────────────────────────────────────────────
WL_VALUES="$ROOT/platform-services/external-dns/workload1-values.yaml"
PLAT_VALUES="$ROOT/platform-services/external-dns/spoke-values.yaml"
HELM_TF="$ROOT/terraform/management/helm.tf"
[ -f "$WL_VALUES" ] || { echo "FAIL: $WL_VALUES missing"; FAIL=1; }

if [ -f "$WL_VALUES" ]; then
  wl_filter="$(yq -r '.domainFilters[0]' "$WL_VALUES")"
  wl_owner="$(yq -r '.txtOwnerId' "$WL_VALUES")"
  wl_prefix="$(yq -r '.txtPrefix' "$WL_VALUES")"

  # workload1 scoping itself.
  case "$wl_filter" in
    workload1.*) echo "ok: workload1 domainFilters scoped to workload1.<domain> ($wl_filter)";;
    *) echo "FAIL: workload1 domainFilters[0] must be workload1.<...> (found: $wl_filter)"; FAIL=1;;
  esac
  [ "$wl_owner" = "k8-platform-workload1" ] && echo "ok: workload1 txtOwnerId = k8-platform-workload1" \
    || { echo "FAIL: workload1 txtOwnerId must be k8-platform-workload1 (found: $wl_owner)"; FAIL=1; }
  { [ -n "$wl_prefix" ] && [ "$wl_prefix" != "null" ]; } && echo "ok: workload1 txtPrefix set ($wl_prefix)" \
    || { echo "FAIL: workload1 txtPrefix must be set (distinct TXT names)"; FAIL=1; }

  # auto-012 IRSA/zone pins (ADR-0010 review: these were missing here while
  # present in the platform file — the drift class the shared AppSet +
  # per-cluster files must not regrow).
  [ "$(yq -r '.serviceAccount.name' "$WL_VALUES")" = "external-dns" ] \
    && echo "ok: workload1 SA name pinned to external-dns (IRSA trust subject)" \
    || { echo "FAIL: workload1 serviceAccount.name must be external-dns (auto-012 IRSA trust)"; FAIL=1; }
  grep -q 'aws-zone-match-parent' "$WL_VALUES" \
    && echo "ok: workload1 sets --aws-zone-match-parent" \
    || { echo "FAIL: workload1 must set --aws-zone-match-parent (subdomain filter on parent zone)"; FAIL=1; }

  # Disjoint from the PLATFORM spoke.
  if [ -f "$PLAT_VALUES" ]; then
    plat_filter="$(yq -r '.domainFilters[0]' "$PLAT_VALUES")"
    plat_owner="$(yq -r '.txtOwnerId' "$PLAT_VALUES")"
    plat_prefix="$(yq -r '.txtPrefix' "$PLAT_VALUES")"
    [ "$wl_owner" != "$plat_owner" ] && echo "ok: workload1 txtOwnerId disjoint from platform ($plat_owner)" \
      || { echo "FAIL: workload1 txtOwnerId collides with platform spoke ($wl_owner)"; FAIL=1; }
    [ "$wl_filter" != "$plat_filter" ] && echo "ok: workload1 domainFilters disjoint from platform ($plat_filter)" \
      || { echo "FAIL: workload1 domainFilters collide with platform spoke ($wl_filter)"; FAIL=1; }
    [ "$wl_prefix" != "$plat_prefix" ] && echo "ok: workload1 txtPrefix disjoint from platform ($plat_prefix)" \
      || { echo "FAIL: workload1 txtPrefix collides with platform spoke ($wl_prefix)"; FAIL=1; }
  else
    echo "FAIL: platform spoke values ($PLAT_VALUES) missing — cannot check disjointness"; FAIL=1
  fi

  # Disjoint from the HUB (terraform/management/helm.tf — k8-platform-mgmt /
  # management.<domain>). Mirror test_external_dns_disjoint_filters.sh extraction.
  [ "$wl_owner" != "k8-platform-mgmt" ] && echo "ok: workload1 txtOwnerId disjoint from hub (k8-platform-mgmt)" \
    || { echo "FAIL: workload1 txtOwnerId collides with the hub (k8-platform-mgmt)"; FAIL=1; }
  case "$wl_filter" in
    management.*) echo "FAIL: workload1 domainFilters overlap the hub's management.<domain>"; FAIL=1;;
    *) echo "ok: workload1 domainFilters disjoint from hub (management.<domain>)";;
  esac
  if [ -f "$HELM_TF" ]; then
    hub_owner_line="$(grep -A2 'name  = "txtOwnerId"' "$HELM_TF" | grep 'value' | head -1)"
    if echo "$hub_owner_line" | grep -q '"k8-platform-mgmt"'; then
      echo "ok: hub txtOwnerId still k8-platform-mgmt (disjoint anchor intact)"
    else
      echo "FAIL: hub txtOwnerId changed unexpectedly (found: $hub_owner_line)"; FAIL=1
    fi
  fi
fi

[ "$FAIL" -eq 0 ] && echo "PASS: workload1 cluster + shared spoke appsets + disjoint external-dns" || echo "FAILED"
exit "$FAIL"
